pipeline {
    agent any

      stages {
          stage('ExecuteTestScript') {
              steps {
                  // Run it!
                  sh 'bash gs-spring-boot/initial/workflow.sh'
              }
         }
    }
}
